
  name: Deploy React code to GitHub Pages
  
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  # You may pin to the exact commit or the version.
  # uses: amitsingh-007/deploy-to-github-pages@bb129748a26581f82d132db7ca88eac4b1651b36
  jobs:
  # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: Deploy React code to GitHub Pages
#           uses: amitsingh-007/deploy-to-github-pages@v1.2
          run: npm run deploy
#   uses: amitsingh-007/deploy-to-github-pages@v1.2


# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the main branch
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
